exports.Home = "/"
exports.main = "/main"
exports.Login = "/login"
exports.Register = "/register"
exports.myTasks = "/tasks/my-tasks"
exports.allTasks = "/tasks/all-tasks"
exports.task= "/tasks/:id"
exports.myFiles = "/files/my-files"
exports.myFiles = "/files/all-files"
exports.file= "/files/:id"
exports.projects = "/projects"
exports.project= "/projects/:id"
exports.clients = "/clients"
exports.client= "/clients/:id"
exports.requests = "/requests"
exports.request= "/requests/:id"
exports.task_meta= '/task/meta/:id'
exports.project_meta= '/project/meta/:id'
exports.request_meta= '/request/meta/:id'